version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_URI: ${DB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
    volumes:
      - ./src:/app/src
    depends_on:
      - mymongo

  mymongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    # volumes:
    #   - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=youappdb
